[package]
name = "target-lexicon-wasm"
version = "0.13.1"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
serde_json = "1.0.138"
target-lexicon = { version = "0.13.1", features = [
    "arch_zkasm",
    "serde_support",
] }
wit-bindgen = "0.38.0"
