name: Create release
on:
  workflow_dispatch:
    inputs:
      draft:
        type: boolean
jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo build --release
      - id: get-version
        uses: mikefarah/yq@master
        with:
          cmd: yq '.package.version' Cargo.toml
      - run: cp -f ./target/wasm32-wasi/release/target_lexicon_wasm.wasm ./target-lexicon.wasm
      - run: gh release create v${{ steps.get-version.outputs.result }} ${{ inputs.draft && '--draft' || ' ' }} --generate-notes ./target-lexicon.wasm
